# Generated by Django 5.0.8 on 2024-12-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asteroid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                ("body_type", models.CharField(max_length=100)),
                ("mass", models.FloatField(null=True)),
                ("diameter", models.FloatField(null=True)),
                ("density", models.FloatField(null=True)),
                ("gravity", models.FloatField(null=True)),
                ("orbit_period", models.FloatField(null=True)),
                ("is_potentially_hazardous", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Astronaut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("craft", models.CharField(max_length=100)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("days_in_space", models.IntegerField(default=0)),
                ("mission", models.CharField(blank=True, max_length=200, null=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Astronot",
                "verbose_name_plural": "Astronotlar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DwarfPlanet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("english_name", models.CharField(max_length=100)),
                ("mass", models.FloatField(null=True)),
                ("radius", models.FloatField(null=True)),
                ("density", models.FloatField(null=True)),
                ("gravity", models.FloatField(null=True)),
                ("escape_velocity", models.FloatField(null=True)),
                ("mean_temperature", models.FloatField(null=True)),
                ("moons_count", models.IntegerField(default=0)),
                ("discovery_date", models.CharField(max_length=100, null=True)),
                ("discovered_by", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ISSLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("people_in_space", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PlanetMoon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("planet_name", models.CharField(max_length=100)),
                ("discovery_date", models.CharField(max_length=100, null=True)),
                ("discovered_by", models.CharField(max_length=200, null=True)),
                ("mass", models.FloatField(null=True)),
                ("radius", models.FloatField(null=True)),
                ("density", models.FloatField(null=True)),
                ("gravity", models.FloatField(null=True)),
                ("is_regular", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlanetRing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planet_name", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("discovery_date", models.CharField(max_length=100, null=True)),
                ("discovered_by", models.CharField(max_length=200, null=True)),
                ("composition", models.CharField(max_length=200, null=True)),
                ("inner_radius", models.FloatField(null=True)),
                ("outer_radius", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Satellite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("discovery_date", models.CharField(blank=True, max_length=100)),
                ("orbital_period", models.FloatField(blank=True, null=True)),
                ("mean_radius", models.FloatField(blank=True, null=True)),
                ("mass", models.FloatField(blank=True, null=True)),
                ("volume", models.FloatField(blank=True, null=True)),
                ("density", models.FloatField(blank=True, null=True)),
                ("gravity", models.FloatField(blank=True, null=True)),
                ("escape_velocity", models.FloatField(blank=True, null=True)),
                ("semi_major_axis", models.FloatField(blank=True, null=True)),
                ("eccentricity", models.FloatField(blank=True, null=True)),
                ("inclination", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SolarSystemBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("english_name", models.CharField(max_length=100)),
                ("body_type", models.CharField(max_length=100)),
                ("mass", models.FloatField(null=True)),
                ("gravity", models.FloatField(null=True)),
                ("mean_radius", models.FloatField(null=True)),
                ("moons_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="SpaceNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                ("published_date", models.DateTimeField()),
                ("news_url", models.URLField()),
                ("image_url", models.URLField()),
            ],
            options={
                "verbose_name_plural": "Space News",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="SpaceXLaunch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mission_name", models.CharField(max_length=200)),
                ("launch_date", models.DateTimeField()),
                ("rocket_name", models.CharField(max_length=100)),
                ("launch_success", models.BooleanField(null=True)),
                ("details", models.TextField(blank=True, null=True)),
                ("mission_patch", models.URLField(blank=True, null=True)),
                ("video_link", models.URLField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-launch_date"],
            },
        ),
    ]
