# Generated by Django 5.0.8 on 2024-12-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Uzay", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Satellite",
        ),
        migrations.AlterModelOptions(
            name="astronaut",
            options={"ordering": ["name"]},
        ),
        migrations.RenameField(
            model_name="astronaut",
            old_name="last_update",
            new_name="last_updated",
        ),
        migrations.RemoveField(
            model_name="astronaut",
            name="country",
        ),
        migrations.RemoveField(
            model_name="astronaut",
            name="craft",
        ),
        migrations.RemoveField(
            model_name="astronaut",
            name="days_in_space",
        ),
        migrations.RemoveField(
            model_name="astronaut",
            name="mission",
        ),
        migrations.RemoveField(
            model_name="astronaut",
            name="title",
        ),
        migrations.AddField(
            model_name="astronaut",
            name="agency",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="astronaut",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="astronaut",
            name="role",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="astronaut",
            name="spacecraft",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="astronaut",
            name="status",
            field=models.CharField(default="active", max_length=20),
        ),
    ]
