# Generated by Django 5.0.8 on 2024-12-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Uzay", "0002_delete_satellite_alter_astronaut_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dwarfplanet",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
